apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.cluster.namespace }}
  name: {{ .Values.cluster.username }}-copy-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "pods/portforward", "pods/proxy", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.cluster.username }}-copy-rolebinding
  namespace: {{ .Values.cluster.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.cluster.username }}
roleRef:
  kind: Role
  name: copy-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.cluster.namespace }}
  name: {{ .Values.cluster.username }}-configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.cluster.namespace }}
  name: {{ .Values.cluster.username }}-configmap-reader-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.cluster.username }}
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io