apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster.username }}-jupyternotebooksvc
  namespace: {{ .Values.cluster.namespace }}
  labels:
    serviceApp: jupyter
    app: cerebro-controller-svc
    user: {{ .Values.cluster.username }}
spec:
  selector:
    app: cerebro-controller
    user: {{ .Values.cluster.username }}
  ports:
    - port: {{ .Values.controller.services.jupyterPort }}
      targetPort: {{ .Values.controller.services.jupyterPort }}
#      nodePort: {{ .Values.controller.services.jupyterNodePort }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster.username }}-tensorboardsvc
  namespace: {{ .Values.cluster.namespace }}
  labels:
    serviceApp: tensorboard
    app: cerebro-controller-svc
    user: {{ .Values.cluster.username }}
spec:
  selector:
    app: cerebro-controller
    user: {{ .Values.cluster.username }}
  ports:
    - port: {{ .Values.controller.services.tensorboardPort }}
      targetPort: {{ .Values.controller.services.tensorboardPort }}
#      nodePort: {{ .Values.controller.services.tensorboardNodePort }}
  type: ClusterIP